version: "3.8"

services:
  web:
    build:
      context: ./backend
    env_file:
      - .env           # w tym pliku jest DATABASE_URL
    volumes:
      - ./backend:/app # opcjonalnie, jeżeli chcesz live-reload przy dev
    ports:
      - "8000:8000"
    # brak depends_on: db ─ nie mamy lokalnego Postgresa