# Generated by Django 5.2.1 on 2025-05-14 19:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Language',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='TVSeries',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='title in English', max_length=256)),
                ('title_og', models.CharField(blank=True, help_text='original title', max_length=256)),
                ('plot', models.TextField(blank=True)),
                ('year', models.IntegerField()),
                ('runtime', models.SmallIntegerField(help_text='minutes', null=True)),
                ('poster_url', models.URLField(blank=True)),
                ('seasons_amount', models.PositiveSmallIntegerField(default=0)),
                ('year_last_season', models.PositiveSmallIntegerField(blank=True, default=None, null=True)),
                ('country', models.ManyToManyField(help_text='country production', to='titles.country')),
                ('languages', models.ManyToManyField(help_text='languages used in film', to='titles.language')),
            ],
            options={
                'abstract': False,
                'unique_together': {('title', 'year')},
            },
        ),
        migrations.CreateModel(
            name='Season',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('season_number', models.PositiveSmallIntegerField(help_text='Season number')),
                ('episodes_count', models.PositiveSmallIntegerField(default=0, help_text='Number of episodes in this season')),
                ('release_date', models.DateField(blank=True, help_text='Release date of this season.', null=True)),
                ('description', models.TextField(blank=True)),
                ('poster_url', models.URLField(blank=True)),
                ('tv_series', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='titles.tvseries')),
            ],
            options={
                'ordering': ['season_number'],
                'unique_together': {('tv_series', 'season_number')},
            },
        ),
        migrations.CreateModel(
            name='Film',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='title in English', max_length=256)),
                ('title_og', models.CharField(blank=True, help_text='original title', max_length=256)),
                ('plot', models.TextField(blank=True)),
                ('year', models.IntegerField()),
                ('runtime', models.SmallIntegerField(help_text='minutes', null=True)),
                ('poster_url', models.URLField(blank=True)),
                ('country', models.ManyToManyField(help_text='country production', to='titles.country')),
                ('languages', models.ManyToManyField(help_text='languages used in film', to='titles.language')),
            ],
            options={
                'abstract': False,
                'unique_together': {('title', 'year')},
            },
        ),
        migrations.CreateModel(
            name='Episode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=256)),
                ('episode_number', models.PositiveSmallIntegerField(help_text='Duration in minutes')),
                ('runtime', models.SmallIntegerField(default=0)),
                ('description', models.TextField(blank=True)),
                ('release_date', models.DateField(blank=True, help_text='Air date of episode', null=True)),
                ('poster_url', models.URLField(blank=True)),
                ('season', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='titles.season')),
            ],
            options={
                'unique_together': {('season', 'episode_number')},
            },
        ),
    ]
