# Generated by Django 5.2.1 on 2025-05-08 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Language',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Film',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=256)),
                ('plot', models.TextField(blank=True)),
                ('year', models.IntegerField()),
                ('runtime', models.SmallIntegerField(help_text='minutes', null=True)),
                ('poster_url', models.URLField(blank=True)),
                ('country', models.ManyToManyField(help_text='country production', to='titles.country')),
                ('languages', models.ManyToManyField(help_text='languages used in film', to='titles.language')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
