# Generated by Django 5.2.1 on 2025-05-15 11:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('titles', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='season',
            name='episodes_count',
        ),
        migrations.RemoveField(
            model_name='tvseries',
            name='seasons_amount',
        ),
    ]
