# Generated by Django 5.2.1 on 2025-05-08 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('titles', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='film',
            name='title_og',
            field=models.CharField(blank=True, help_text='original title', max_length=256),
        ),
        migrations.AlterField(
            model_name='film',
            name='title',
            field=models.CharField(help_text='title in English', max_length=256),
        ),
    ]
