# Generated by Django 5.2.1 on 2025-05-08 15:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('titles', '0002_film_title_og_alter_film_title'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='film',
            unique_together={('title', 'year')},
        ),
    ]
