# Generated by Django 5.2.1 on 2025-05-15 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('titles', '0002_remove_season_episodes_count_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='season',
            name='release_date',
            field=models.DateField(blank=True, help_text='Air date of episode', null=True),
        ),
    ]
