# Generated by Django 5.2.1 on 2025-05-15 16:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('titles', '0003_alter_season_release_date'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='episode',
            options={'ordering': ['episode_number']},
        ),
        migrations.AlterModelOptions(
            name='film',
            options={'ordering': ['title']},
        ),
        migrations.AlterModelOptions(
            name='tvseries',
            options={'ordering': ['title']},
        ),
        migrations.AlterField(
            model_name='episode',
            name='episode_number',
            field=models.PositiveSmallIntegerField(),
        ),
        migrations.AlterField(
            model_name='episode',
            name='release_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='episode',
            name='season',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='episodes', to='titles.season'),
        ),
        migrations.AlterField(
            model_name='film',
            name='country',
            field=models.ManyToManyField(to='titles.country'),
        ),
        migrations.AlterField(
            model_name='film',
            name='languages',
            field=models.ManyToManyField(to='titles.language'),
        ),
        migrations.AlterField(
            model_name='film',
            name='runtime',
            field=models.SmallIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='film',
            name='title',
            field=models.CharField(max_length=256),
        ),
        migrations.AlterField(
            model_name='film',
            name='title_og',
            field=models.CharField(blank=True, max_length=256),
        ),
        migrations.AlterField(
            model_name='season',
            name='release_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='season',
            name='season_number',
            field=models.PositiveSmallIntegerField(),
        ),
        migrations.AlterField(
            model_name='season',
            name='tv_series',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='seasons', to='titles.tvseries'),
        ),
        migrations.AlterField(
            model_name='tvseries',
            name='country',
            field=models.ManyToManyField(to='titles.country'),
        ),
        migrations.AlterField(
            model_name='tvseries',
            name='languages',
            field=models.ManyToManyField(to='titles.language'),
        ),
        migrations.AlterField(
            model_name='tvseries',
            name='runtime',
            field=models.SmallIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='tvseries',
            name='title',
            field=models.CharField(max_length=256),
        ),
        migrations.AlterField(
            model_name='tvseries',
            name='title_og',
            field=models.CharField(blank=True, max_length=256),
        ),
        migrations.AlterField(
            model_name='tvseries',
            name='year_last_season',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
    ]
