# Generated by Django 5.0.1 on 2025-10-11 16:04

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('slug', models.SlugField(unique=True)),
            ],
            options={
                'db_table': 'genres',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(db_index=True, max_length=255)),
                ('og_title', models.CharField(blank=True, max_length=255)),
                ('overview', models.TextField(blank=True)),
                ('poster', models.ImageField(blank=True, null=True, upload_to='posters/')),
                ('backdrop', models.ImageField(blank=True, null=True, upload_to='backdrops/')),
                ('status', models.CharField(choices=[('released', 'Released'), ('ongoing', 'Ongoing'), ('upcoming', 'Upcoming')], default='released', max_length=20)),
                ('adult', models.BooleanField(default=False)),
                ('vote_average', models.DecimalField(decimal_places=1, default=0, max_digits=3)),
                ('vote_count', models.IntegerField(default=0)),
                ('popularity', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('release_date', models.DateField(blank=True, null=True)),
                ('runtime', models.IntegerField(blank=True, help_text='Runtime in minutes', null=True, validators=[django.core.validators.MinValueValidator(1)])),
                ('budget', models.BigIntegerField(blank=True, null=True)),
                ('revenue', models.BigIntegerField(blank=True, null=True)),
                ('genres', models.ManyToManyField(blank=True, related_name='%(class)s_set', to='movies.genre')),
            ],
            options={
                'db_table': 'movies',
                'ordering': ['release_date', ['-popularity']],
                'indexes': [models.Index(fields=['-release_date', '-popularity'], name='movies_release_351dba_idx'), models.Index(fields=['title'], name='movies_title_179e04_idx')],
            },
        ),
    ]
