# Generated by Django 5.0.1 on 2025-10-12 19:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movie',
            name='backdrop',
        ),
        migrations.RemoveField(
            model_name='movie',
            name='backdrop_url',
        ),
        migrations.RemoveField(
            model_name='movie',
            name='poster',
        ),
        migrations.RemoveField(
            model_name='movie',
            name='poster_url',
        ),
        migrations.RemoveField(
            model_name='person',
            name='photo_url',
        ),
    ]
