# Generated by Django 5.0.1 on 2025-10-12 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0002_remove_image_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='background',
            field=models.ImageField(blank=True, help_text='Background image (larger)', null=True, upload_to='backgrounds/'),
        ),
        migrations.AddField(
            model_name='movie',
            name='poster',
            field=models.ImageField(blank=True, help_text='Poster image (smaller)', null=True, upload_to='posters/'),
        ),
        migrations.AddField(
            model_name='person',
            name='avatar',
            field=models.ImageField(blank=True, help_text='Actor/Director photo', null=True, upload_to='avatars/'),
        ),
    ]
